### ISSUE TITLE
Data visualization not occurring upon package loading

### ISSUE THREAD

**Issue by NicoSan2304** [datasketch/hgmagic#1]
Al momento de utilizar el paquete con datos específicos, no se realizó la visualización de los mismos. 
Revisé los testthat para correr el código y en el entorno del paquete funciona bien, pero al llevarlo a otro entorno/proyecto de R al parecer no se visualizan los datos,

**Entorno propio:**
![image](https://github.com/datasketch/hgmagic/assets/155469312/59169527-20f5-4721-8d54-8817dab2b815)

**Entorno hgmagic**
![image](https://github.com/datasketch/hgmagic/assets/155469312/21b0d89c-2385-4117-9d2d-7341f02a359a)

**Comment by CamilaAchuri** [comment]
@NicoSan2304 Por favor poner un ejemplo reproducible, 
no es necesario que hagas un `as.data.frame` de ht$dd,
escribir cuales son los unicos resultados de la variable que quiere
graficar.
